// client/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username = '';
  password = '';

  constructor(private router: Router) {}

  handleSubmit(event: Event) {
    event.preventDefault();
    console.log('Login:', { username: this.username, password: this.password });
    this.router.navigate(['/modules']);
  }
}

<div 
  class="min-h-screen flex items-center justify-center relative"
  style="background-image: url('https://11care.com.br/wp-content/uploads/2025/10/Artigo-Profissionalizacao-da-enfermagem.jpg.webp'); background-size: cover; background-position: center;"
>
  <div class="absolute inset-0" style="background: rgba(0, 86, 179, 0.1);"></div>
  
  <div class="relative z-10 w-full max-w-[420px] px-5">
    <div class="bg-white rounded-xl shadow-2xl p-8">
      <div class="text-center mb-8">
        <img 
          src="https://11care.com.br/wp-content/uploads/2024/05/logo-11Care-azul-1024x249.png.webp"
          alt="11Care Logo"
          class="max-w-[280px] mx-auto mb-5"
        />
        <h1 class="text-[32px] font-bold mb-2" style="color: var(--primary-blue);">
          Plataforma de Enfermagem
        </h1>
        <p class="text-base" style="color: var(--neutral-gray);">
          Sistema integrado de gestão hospitalar
        </p>
      </div>

      <form (ngSubmit)="handleSubmit($event)" data-testid="form-login">
        <div class="space-y-6">
          <div class="space-y-2">
            <label for="username" class="block text-sm font-semibold" style="color: var(--text-gray);">
              Usuário
            </label>
            <input
              id="username"
              type="text"
              [(ngModel)]="username"
              name="username"
              placeholder="Digite seu usuário"
              class="search-input"
              style="width: 100%; padding-left: 14px !important;"
              data-testid="input-username"
              required
            />
          </div>

          <div class="space-y-2">
            <label for="password" class="block text-sm font-semibold" style="color: var(--text-gray);">
              Senha
            </label>
            <input
              id="password"
              type="password"
              [(ngModel)]="password"
              name="password"
              placeholder="Digite sua senha"
              class="search-input"
              style="width: 100%; padding-left: 14px !important;"
              data-testid="input-password"
              required
            />
          </div>

          <button 
            type="submit" 
            class="w-full py-3.5 text-base font-semibold text-white rounded-lg gradient-button"
            data-testid="button-login"
          >
            ENTRAR
          </button>
        </div>
      </form>

      <div class="mt-8 pt-5 text-center text-sm" style="border-top: 1px solid var(--border-gray); color: var(--neutral-gray);">
        <p>© 2025 11Care - Todos os direitos reservados</p>
      </div>
    </div>
  </div>
</div>

// client/src/pages/login.tsx
import { useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";

export default function LoginPage() {
  const [, setLocation] = useLocation();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("Login:", { username, password });
    setLocation("/modules");
  };

  return (
    <div 
      className="min-h-screen flex items-center justify-center relative"
      style={{
        backgroundImage: 'url("https://11care.com.br/wp-content/uploads/2025/10/Artigo-Profissionalizacao-da-enfermagem.jpg.webp")',
        backgroundSize: 'cover',
        backgroundPosition: 'center'
      }}
    >
      <div className="absolute inset-0 bg-primary/10" />
      
      <div className="relative z-10 w-full max-w-md px-5">
        <Card className="p-8">
          <div className="text-center mb-8">
            <img 
              src="https://11care.com.br/wp-content/uploads/2024/05/logo-11Care-azul-1024x249.png.webp"
              alt="11Care Logo"
              className="max-w-[280px] mx-auto mb-6"
            />
            <h1 className="text-[32px] font-bold text-primary mb-2">
              Plataforma de Enfermagem
            </h1>
            <p className="text-muted-foreground text-base">
              Sistema integrado de gestão hospitalar
            </p>
          </div>

          <form onSubmit={handleSubmit} data-testid="form-login">
            <div className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="username" className="text-sm font-semibold">
                  Usuário
                </Label>
                <Input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  placeholder="Digite seu usuário"
                  className="h-[50px] text-base"
                  data-testid="input-username"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="password" className="text-sm font-semibold">
                  Senha
                </Label>
                <Input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Digite sua senha"
                  className="h-[50px] text-base"
                  data-testid="input-password"
                  required
                />
              </div>

              <Button 
                type="submit" 
                className="w-full h-12 text-base font-semibold"
                data-testid="button-login"
              >
                Entrar
              </Button>
            </div>
          </form>

          <div className="mt-8 pt-6 border-t text-center text-sm text-muted-foreground">
            <p>© 2025 11Care - Todos os direitos reservados</p>
          </div>
        </Card>
      </div>
    </div>
  );
}
